### ISSUE TITLE
fixed total price issue

### ISSUE THREAD

**Issue by EGBluesman** [ash2osh/atfawry_woocomerce#1]
When I installed the "fixed total price issue" update,
![payment 2](https://user-images.githubusercontent.com/41054899/42505626-9d3b3ba2-843f-11e8-9008-934df577ce7e.jpeg)
![payment1](https://user-images.githubusercontent.com/41054899/42505627-9d61f2c4-843f-11e8-89db-40ff62b84fcb.jpeg)
![order](https://user-images.githubusercontent.com/41054899/42505628-9d8573e8-843f-11e8-98f0-c40475372082.jpeg)

 it worked fine but only once!! Then again the total price miscalculation happens again!! you will notice that the amount that shows in the end at the payment screen is only the total of the items which is 775 in quotation before adding Customs, Tax, shipping and service fee.

**Comment by ash2osh** [comment]
ok i am testing the issue 
i will give you feedback ASAP

**Comment by ash2osh** [comment]
[Ecommerce Technical Guide_V2.10.pdf](https://github.com/ash2osh/atfawry_woocomerce/files/2191890/Ecommerce.Technical.Guide_V2.10.pdf)
### since the document i have from fawry does not support shipping nor taxes 
so i decided to add stupid mode 
![image](https://user-images.githubusercontent.com/5173263/42681261-7bbe5faa-8687-11e8-95d3-69814e3fb3ee.png)

this mode will take only the total price(including everything) and send the order ID as product SKU
to fawry

**Comment by EGBluesman** [comment]
Thank you for the quick turn around! It should be working fine now!
